pipeline {
    agent any
    environment {
        ANSIBLE_HOST_KEY_CHECKING = 'False'
    }
    stages {
        stage('Run Ansible Playbook') {
            steps {
                sh 'ansible-playbook -i inventory/inventory.ini playbooks/setup_nginx.yml'
            }
        }
    }
}
